Change argument immutable.Seq to general Seq
* compile error
* source problem is akka-http required immutable.Seq

```
[error]
/Users/knishida/code/_great_libraries/drunk/src/main/scala/com/github/jarlakxen/drunk/backend/AkkaConnectionBackend.scala:24:17:
type mismatch;
[error]  found   : Seq[akka.http.scaladsl.model.HttpHeader] (in
scala.collection)
[error]  required: Seq[akka.http.scaladsl.model.HttpHeader] (in
scala.collection.immutable)
[error]       headers = headers,
[error]                 ^
[error]
/Users/knishida/code/_great_libraries/drunk/src/main/scala/com/github/jarlakxen/drunk/backend/AkkaHttpBackend.scala:35:50:
type mismatch;
[error]  found   : Seq[akka.http.scaladsl.model.HttpHeader] (in
scala.collection)
[error]  required: Seq[akka.http.scaladsl.model.HttpHeader] (in
scala.collection.immutable)
[error]     val req = HttpRequest(HttpMethods.POST, uri, headers,
HttpEntity(ContentTypes.`application/json`, body))
[error]                                                  ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 24 s, completed 2019/06/27 10:35:31
```